Upgrade to Ruby 3.3.4 (#60329)
* ruby => 3.3.4

* Gemfile.lock: `bundle update cld`, cld => 0.13.0

* Gemfile.lock: `bundle update css_parser`, File.exists? no longer exists

* yaml.rb: YAML.load only takes one arg with psych

* Gemfile: eyes_selenium => 6.3.7 + `bundle update eyes_selenium` updates selenium-webdriver to 4.10.0

* bin/dashboard-server loads studio

* remove our custom fork of sprockets (backport of rails 4=>3, outdated anyway) which was spewing warnings to console

* pycall => 1.5.2

* ChatClient: print messages in dev too

* Remove workaround from Gemfile marked 'This is a temporary workaround - remove when bundler version is >=2.0'

* Gemfile.lock: bundle => 2.5.17

* Remove unnecessary (?) `gem install bundler` step from SETUP.md

* Dockerfile: ruby => 3.3.4, and remove unnecessary manual install of bundle version (bundle does this automatically to match Gemfile.lock bundled with on bundle install)

* .drone.yml: use codedotorg/code-dot-org:ruby-3.3.4

* cookbooks: set ruby to 3.3.4, rake to 13.2.1, bundle to 2.5.17 and gem to 3.5.17
Gem is an interesting case, the default gem version with ruby with 3.3.4 is 3.5.11, but a previous update of default.rb by Elijah had trouble unless a version of rubygem was specified that was NOT the system version, see: bf41ebfcda92dcb5bfc6673ef016e5f9625ae843

* Redo rake => 13.2.1 upgrade in /Gemfile

* cdo-ruby/.kitchen.yml: use ubuntu-20.04

* cdo-ruby/.kitchen.yml: enable serverspec verifier (currently was disabled = no verification)
cdo-ruby/ ruby_spec.rb: verify versions

* cdo-ruby ruby-build.rb: bump RUBY_BUILD_VERSION to 20240727 so it knows about Ruby 3.3.4.

* cdo-ruby ruby-build.rb: include RUBY_BUILD_VERSION in tarball names or chef will ignore if files already exist from a previous version

* cdo-ruby ruby-build: switch from serverspec to inspec which we generally use

* cdo-ruby ruby-build.rb: install apt-package list from https://github.com/rbenv/ruby-build/wiki#ubuntudebianmint => build not broken

* ruby_spec.rb: convert from serverspec to inspec

* honeybadger.yml: ensure API key is a string not an int, dev values of "000000" were turning into the int 0 which confuses the poor badger

* Fix pre-Ruby-3.4 warnings: "___ was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0"

* Gemfile: redcarpet =>3.6.0 to fix a warning, see: https://www.redmine.org/issues/38118

* cookbooks/.ruby-version: bump to 3.3.4

* `bundle update docker-api excon` to fix `kitchen create` for dokken driver

* cookbooks/Gemfile: explicitly require racc, an undeclared dep of test-kitchen 3.4.0. See: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282210718

* cookbooks/Gemfile.lock: `bundle update berkshelf`

* cloud_formation.rb: add Date to YAML.load permitted_classes to fix `rake adhoc:start`

* Gemfile: highline => 3.1.0, fixes warnings on `rake adhoc:start`, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282228816

* Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277

* Gemfile: add explicit `syslog` to fix Ruby 3.4 deprecation warnings

* profanity_privacy_helper: disable for Java Lab etc, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282270302

* Revert "Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277"

This reverts commit 9ac1087278a4aa7573b4c990d3377336d5441433.

* Check the honeybadger backend as the test runs

* Gemfile.lock: `bundle update rubocop`

* honeybadger_test: assert_equal 'test', config.backend

* honeybadger_test: print extensive debug spew

* honeybadger_test: search notices for one from honeybadger_error controller

* generateSharedConstants.rb: `require 'ostruct'`

* .rubocop_[todo|new].yml: update for rubocop 1.65

* honeybadger_test: cast notice to json before using

* Gemfile.lock: `bundle update vcr`

* fake_dashboard.rb: fix Psych::AliasesNotEnabled: Alias parsing was not enabled.

* pegasus/honeybadger.yml: fix NoMethodError: undefined method `=~' for an instance of Integer

* pegasus page.haml: fix undefined method `exists?' for class File

* Gemfile: image_optim apply ruby 3.1 backport to our custom fork

* to_crowdin_yaml: accept that 'yes' example will now be "yes"

* `bundle install`

* Gemfile.lock: `bundle update cld`, cld => 0.13.0

* Gemfile.lock: `bundle update css_parser`, File.exists? no longer exists

* yaml.rb: YAML.load only takes one arg with psych

* Gemfile: eyes_selenium => 6.3.7 + `bundle update eyes_selenium` updates selenium-webdriver to 4.10.0

* bin/dashboard-server loads studio

* remove our custom fork of sprockets (backport of rails 4=>3, outdated anyway) which was spewing warnings to console

* pycall => 1.5.2

* ChatClient: print messages in dev too

* Remove workaround from Gemfile marked 'This is a temporary workaround - remove when bundler version is >=2.0'

* Gemfile.lock: bundle => 2.5.17

* Remove unnecessary (?) `gem install bundler` step from SETUP.md

* Redo rake => 13.2.1 upgrade in /Gemfile

* honeybadger.yml: ensure API key is a string not an int, dev values of "000000" were turning into the int 0 which confuses the poor badger

* Fix pre-Ruby-3.4 warnings: "___ was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0"

* Gemfile: redcarpet =>3.6.0 to fix a warning, see: https://www.redmine.org/issues/38118

* `bundle update docker-api excon` to fix `kitchen create` for dokken driver

* cloud_formation.rb: add Date to YAML.load permitted_classes to fix `rake adhoc:start`

* Gemfile: highline => 3.1.0, fixes warnings on `rake adhoc:start`, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282228816

* Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277

* Gemfile: add explicit `syslog` to fix Ruby 3.4 deprecation warnings

* profanity_privacy_helper: disable for Java Lab etc, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282270302

* Revert "Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277"

This reverts commit 9ac1087278a4aa7573b4c990d3377336d5441433.

* Check the honeybadger backend as the test runs

* Gemfile.lock: `bundle update rubocop`

* honeybadger_test: assert_equal 'test', config.backend

* honeybadger_test: print extensive debug spew

* honeybadger_test: search notices for one from honeybadger_error controller

* generateSharedConstants.rb: `require 'ostruct'`

* .rubocop_[todo|new].yml: update for rubocop 1.65

* honeybadger_test: cast notice to json before using

* Gemfile.lock: `bundle update vcr`

* fake_dashboard.rb: fix Psych::AliasesNotEnabled: Alias parsing was not enabled.

* pegasus/honeybadger.yml: fix NoMethodError: undefined method `=~' for an instance of Integer

* pegasus page.haml: fix undefined method `exists?' for class File

* Gemfile: image_optim apply ruby 3.1 backport to our custom fork

* honeybadger_test: fix elijah review suggestions, comment changes to test

* Gemfile: fix elijah review suggestions, move Ruby 3.4 deprecation gems to top

* Gemfile: switch image_optim back to cdo branch

* `bundle install`

* `bundle install`

* Gemfile: fix elijah review suggestions, move Ruby 3.4 deprecation gems to top

* honeybadger_test: fix elijah review suggestions, comment changes to test

* Gemfile: switch image_optim back to cdo branch

* Revert "ChatClient: print messages in dev too"

This reverts commit 346468a87445e6f9ac4ba26fdd5901488319ba23.

* Revert "ChatClient: print messages in dev too"

This reverts commit 346468a87445e6f9ac4ba26fdd5901488319ba23.

* cookbooks/Gemfile and Gemfile.lock: reduce diff with ruby-3.3

* cdo-ruby/.kitchen.yml: use ubuntu-20.04

* cdo-ruby/.kitchen.yml: enable serverspec verifier (currently was disabled = no verification)
cdo-ruby/ ruby_spec.rb: verify versions

* cdo-ruby ruby-build: switch from serverspec to inspec which we generally use

* ruby_spec.rb: convert from serverspec to inspec

* cookbooks/cdo-ruby ruby_spec.rb: switch back to verifying ruby 3.0.5 versions

* Gemfile.lock: `bundle install`, removes oily_png automatically

* cloud_formation.rb: work on ruby 3.0.5 AND 3.3.4

* Revert "Revert "Ruby 3.3.4: pre-upgrade everything that can apply to Ruby 3.0…"

This reverts commit 4652ab2d989c1dbaa30d37301490660a114b97a8.

* browsers.json: run Firefox tests on Windows 11, workaround sauce VM issue

* full_page_test.rb: temporary test script for debugging applitools eyes

* full_page_test.rb: rubocop

* eyes_steps.rb: try to fix eyes tests not being full page [test eyes]

* full_page_test.rb: update to latest

* [test eyes] now that baselines are updated

* [test eyes][test firefox]

* [test eyes][test firefox]

* Revert "Revert "Ruby 3.3.4: pre-upgrade everything that can apply to Ruby 3.0.5 too (…" (#60731)"

This reverts commit 64033753ebe2724a8aa42d296f9c4ca0a0f72949.

* [test eyes][test firefox]

* Gemfile.lock: use new aws-sdk-core and aws-partitions

* downgrade eyes_selenium => 3.18.4

* Revert eyes_selenium 6.3.7 upgrade

* .drone.yml: correct merge error

* chmod +x entrypoint.sh

* restore perms on entrypoint.sh

* rerun drone after rebuilding dockerfile

* entrypoint.sh: chmod +x, see https://github.com/code-dot-org/code-dot-org/pull/57243/files#diff-4ea247e90f575faac33fa57ed16ba7c1a0eb9e5dabdd6598c7d61d2b7b818b5c, which I believe accidentally removed the x bit from entrypoint.sh

* Use image name: codedotorg/code-dot-org:1.11.0

* Monkeypatch `state_machine` Gem

We're using a very old version of `eyes_selenium`, which in turn depends
on an outdated `state_machine` gem which lacks support for Ruby >= 3.2.
More-recent versions of `eyes_selenium` use the new `state_machines`
gem (note the plural), which does support current Ruby. Until we're able
to get our `eyes_selenium` upgraded (which we should do promptly), we
add a temporary patch.

* Back out selenium upgrade (see https://github.com/code-dot-org/code-dot-org/pull/61802)

* match staging except for Ruby upgrade itself

* docker/README.md: make architecture explicit (so it works on non-x86 too)

* codedotorg/code-dot-org:1.12.0

* Always use bundler version from ruby-build

* cookbooks/cdo-ruby: remove bundler_version attr

* Only monkeypatch the state_machine gem when it is present (= in dev and test)

---------

Co-authored-by: Elijah Hamovitz <elijahhamovitz@gmail.com>